name: 'tag name'
description: 'tag name by git branch'
author: 'qi'
inputs:
  refs: "refs/head/main"
    required: true
    description: 'input git branch here'
    default: 'refs/head/main'
outputs:
  tag:
      description: 'tag name'
runs:
  using: 'node12'
  main: 'dist/index.js'
